In [1]:
import torch
import numpy as np
print('-------------')  
print('Mul vs Matmul')  
print('-------------')  
m1 = torch.FloatTensor([[1, 2], [3, 4]])  
m2 = torch.FloatTensor([[1], [2]])  
print('Shape of Matrix 1: ', m1.shape) # 2 x 2  
print('Shape of Matrix 2: ', m2.shape) # 2 x 1  
print(m1.matmul(m2)) # 2 x 1  

m1 = torch.FloatTensor([[1, 2], [3, 4]])  
m2 = torch.FloatTensor([[1], [2]])  
print('Shape of Matrix 1: ', m1.shape) # 2 x 2  
print('Shape of Matrix 2: ', m2.shape) # 2 x 1  
print(m1 * m2) # 2 x 2  
print(m1.mul(m2))  


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## 선형회귀

In [2]:
# 가장 기본적인 선형회귀
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
# 재사용을 위해 랜덤값을 초기화
torch.manual_seed(1)


In [3]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[3], [6], [9]])

In [4]:
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
hypothesis = x_train * W + b

In [5]:
cost = torch.mean((hypothesis - y_train) ** 2)
optimizer = optim.SGD([W, b], lr=0.01)

In [ ]:
nb_

## Reference
- [PyTorch tutorial](https://tutorials.pytorch.kr/beginner/basics/tensorqs_tutorial.html)

- [모두를 위한 딥러닝 시즌2](https://github.com/deeplearningzerotoall/PyTorch)

- [PyTorch로 시작하는 딥 러닝 입문](https://wikidocs.net/book/2788)