In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import SGD



In [5]:
# raw data loading
df = pd.read_csv('admission.csv')

# 데이터 전처리
# 결측치 처리
train_data = df.dropna(how='any')

# 이상치 처리

# 정규화
x_data = df.drop('admit', axis=1, inplace=False).values
t_data = df['admit'].values.reshape(-1, 1)

scaler_x = MinMaxScaler()
scaler_x.fit(x_data)

x_data_norm = scaler_x.transform(x_data)
print(x_data_norm)

[[0.27586207 0.77586207 0.66666667]
 [0.75862069 0.81034483 0.66666667]
 [1.         1.         0.        ]
 ...
 [0.4137931  0.21264368 0.33333333]
 [0.82758621 0.79885057 0.33333333]
 [0.65517241 0.93678161 0.66666667]]


In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.optimizers import SGD
# Flatten Layer를 이용해서 input layer를 표현 

keras_model = Sequential()

keras_model.add(Flatten(input_shape=(3, )))
keras_model.add(Dense(1, activation='sigmoid'))

# model 설정(model의 정확도 평가)
keras_model.compile(optimizer=SGD(learning_rate=1e-4), loss='binary_crossentropy', metrics=['accuracy'])

keras_model.fit(x_data_norm, t_data, epochs=1000, verbose=1)

Epoch 1/1000
13/13 [==============================] - 1s 2ms/step - loss: 0.8703 - accuracy: 0.3200
Epoch 2/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8700 - accuracy: 0.3200
Epoch 3/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8697 - accuracy: 0.3200
Epoch 4/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8693 - accuracy: 0.3200
Epoch 5/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8690 - accuracy: 0.3200
Epoch 6/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8686 - accuracy: 0.3200
Epoch 7/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8683 - accuracy: 0.3200
Epoch 8/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8679 - accuracy: 0.3200
Epoch 9/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8676 - accuracy: 0.3200
Epoch 10/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8672 - accuracy: 0.3200

13/13 [==============================] - 0s 2ms/step - loss: 0.8436 - accuracy: 0.3225
Epoch 83/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8433 - accuracy: 0.3225
Epoch 84/1000
13/13 [==============================] - 0s 3ms/step - loss: 0.8430 - accuracy: 0.3225
Epoch 85/1000
13/13 [==============================] - 0s 3ms/step - loss: 0.8427 - accuracy: 0.3225
Epoch 86/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8423 - accuracy: 0.3225
Epoch 87/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8420 - accuracy: 0.3225
Epoch 88/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8417 - accuracy: 0.3225
Epoch 89/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8414 - accuracy: 0.3225
Epoch 90/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8411 - accuracy: 0.3225
Epoch 91/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8408 - accuracy: 0.3225
Epoc

13/13 [==============================] - 0s 1ms/step - loss: 0.8196 - accuracy: 0.3250
Epoch 163/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.8193 - accuracy: 0.3250
Epoch 164/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8191 - accuracy: 0.3250
Epoch 165/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8188 - accuracy: 0.3250
Epoch 166/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8185 - accuracy: 0.3250
Epoch 167/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.8182 - accuracy: 0.3250
Epoch 168/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.8179 - accuracy: 0.3250
Epoch 169/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.8176 - accuracy: 0.3250
Epoch 170/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8174 - accuracy: 0.3250
Epoch 171/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.8171 - accuracy: 0.

13/13 [==============================] - 0s 1ms/step - loss: 0.7979 - accuracy: 0.3250
Epoch 243/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7977 - accuracy: 0.3250
Epoch 244/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7974 - accuracy: 0.3250
Epoch 245/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7971 - accuracy: 0.3250
Epoch 246/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7969 - accuracy: 0.3250
Epoch 247/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7966 - accuracy: 0.3250
Epoch 248/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7963 - accuracy: 0.3250
Epoch 249/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7961 - accuracy: 0.3250
Epoch 250/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7958 - accuracy: 0.3250
Epoch 251/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7956 - accuracy: 0.

13/13 [==============================] - 0s 2ms/step - loss: 0.7782 - accuracy: 0.3425
Epoch 323/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7779 - accuracy: 0.3425
Epoch 324/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7777 - accuracy: 0.3450
Epoch 325/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7775 - accuracy: 0.3450
Epoch 326/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7773 - accuracy: 0.3450
Epoch 327/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7770 - accuracy: 0.3450
Epoch 328/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7768 - accuracy: 0.3450
Epoch 329/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7766 - accuracy: 0.3450
Epoch 330/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7763 - accuracy: 0.3450
Epoch 331/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7761 - accuracy: 0.

13/13 [==============================] - 0s 2ms/step - loss: 0.7604 - accuracy: 0.3600
Epoch 403/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7602 - accuracy: 0.3625
Epoch 404/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7600 - accuracy: 0.3650
Epoch 405/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7598 - accuracy: 0.3650
Epoch 406/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7596 - accuracy: 0.3650
Epoch 407/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7594 - accuracy: 0.3650
Epoch 408/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7592 - accuracy: 0.3650
Epoch 409/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7590 - accuracy: 0.3650
Epoch 410/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7588 - accuracy: 0.3650
Epoch 411/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7586 - accuracy: 0.

13/13 [==============================] - 0s 2ms/step - loss: 0.7444 - accuracy: 0.3925
Epoch 483/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7442 - accuracy: 0.3925
Epoch 484/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7440 - accuracy: 0.3925
Epoch 485/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7438 - accuracy: 0.3925
Epoch 486/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7436 - accuracy: 0.3925
Epoch 487/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7435 - accuracy: 0.3950
Epoch 488/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7433 - accuracy: 0.3950
Epoch 489/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7431 - accuracy: 0.3950
Epoch 490/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7429 - accuracy: 0.3950
Epoch 491/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7427 - accuracy: 0.

13/13 [==============================] - 0s 2ms/step - loss: 0.7299 - accuracy: 0.4150
Epoch 563/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7298 - accuracy: 0.4150
Epoch 564/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7296 - accuracy: 0.4150
Epoch 565/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7294 - accuracy: 0.4150
Epoch 566/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7293 - accuracy: 0.4150
Epoch 567/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7291 - accuracy: 0.4150
Epoch 568/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7289 - accuracy: 0.4150
Epoch 569/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7287 - accuracy: 0.4150
Epoch 570/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7286 - accuracy: 0.4150
Epoch 571/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7284 - accuracy: 0.

13/13 [==============================] - 0s 2ms/step - loss: 0.7169 - accuracy: 0.4425
Epoch 643/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7167 - accuracy: 0.4425
Epoch 644/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7166 - accuracy: 0.4425
Epoch 645/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7164 - accuracy: 0.4450
Epoch 646/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7163 - accuracy: 0.4450
Epoch 647/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7161 - accuracy: 0.4450
Epoch 648/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7160 - accuracy: 0.4475
Epoch 649/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7158 - accuracy: 0.4475
Epoch 650/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7157 - accuracy: 0.4475
Epoch 651/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7155 - accuracy: 0.

13/13 [==============================] - 0s 2ms/step - loss: 0.7052 - accuracy: 0.4775
Epoch 723/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7051 - accuracy: 0.4775
Epoch 724/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7049 - accuracy: 0.4775
Epoch 725/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7048 - accuracy: 0.4800
Epoch 726/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.7047 - accuracy: 0.4800
Epoch 727/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7045 - accuracy: 0.4800
Epoch 728/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7044 - accuracy: 0.4800
Epoch 729/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7042 - accuracy: 0.4800
Epoch 730/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7041 - accuracy: 0.4800
Epoch 731/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.7040 - accuracy: 0.

13/13 [==============================] - 0s 2ms/step - loss: 0.6947 - accuracy: 0.5175
Epoch 803/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6946 - accuracy: 0.5175
Epoch 804/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6944 - accuracy: 0.5175
Epoch 805/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6943 - accuracy: 0.5200
Epoch 806/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6942 - accuracy: 0.5200
Epoch 807/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6941 - accuracy: 0.5225
Epoch 808/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6939 - accuracy: 0.5225
Epoch 809/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6938 - accuracy: 0.5225
Epoch 810/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.6937 - accuracy: 0.5225
Epoch 811/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6936 - accuracy: 0.

13/13 [==============================] - 0s 2ms/step - loss: 0.6852 - accuracy: 0.5425
Epoch 883/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6851 - accuracy: 0.5475
Epoch 884/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6850 - accuracy: 0.5475
Epoch 885/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6849 - accuracy: 0.5475
Epoch 886/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.6848 - accuracy: 0.5475
Epoch 887/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6847 - accuracy: 0.5500
Epoch 888/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6846 - accuracy: 0.5500
Epoch 889/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6844 - accuracy: 0.5525
Epoch 890/1000
13/13 [==============================] - 0s 1ms/step - loss: 0.6843 - accuracy: 0.5525
Epoch 891/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6842 - accuracy: 0.

13/13 [==============================] - 0s 2ms/step - loss: 0.6767 - accuracy: 0.5700
Epoch 963/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6766 - accuracy: 0.5675
Epoch 964/1000
13/13 [==============================] - 0s 3ms/step - loss: 0.6765 - accuracy: 0.5675
Epoch 965/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6764 - accuracy: 0.5675
Epoch 966/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6763 - accuracy: 0.5675
Epoch 967/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6762 - accuracy: 0.5700
Epoch 968/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6761 - accuracy: 0.5725
Epoch 969/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6760 - accuracy: 0.5750
Epoch 970/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6759 - accuracy: 0.5750
Epoch 971/1000
13/13 [==============================] - 0s 2ms/step - loss: 0.6758 - accuracy: 0.