In [1]:
import numpy as np

### ndarray 생성

In [20]:
list1 = [1, 2, 3]
type(list1)

array1 = np.array(list1)
#array1 = np.array([1,2,3])

print(type(array1))
print(array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print(type(array2))
print(array2.shape)

array3 = np.array([[1,2,3]])
print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)
<class 'numpy.ndarray'>
(1, 3)


In [12]:
array1.ndim, array2.ndim, array3.ndim # 차원 개수

(1, 2, 2)

### ndarray data type

In [21]:
list1 = [1,2,3]
array1 = np.array(list1)
array1, array1.dtype

(array([1, 2, 3]), dtype('int32'))

In [29]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) # 문자열 array

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # float array

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [31]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # array_int.astype(np.float64)
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [8]:
sequence_array = np.arange(10)
sequence_array
sequence_array.dtype, sequence_array.shape

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [9]:
#(3, 2) shape을 가지는 모든 원소가 0, dtype은 int32 인 ndarray 생성.  
zero_array = np.zeros((3, 2), dtype='int32')
zero_array
zero_array.dtype, zero_array.shape

#(3, 2) shape을 가지는 모든 원소가 1인 ndarray 생성. ,
one_array = np.ones((3, 2))
one_array
one_array.dtype, one_array.shape

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)
